CREATE TABLE USERS(
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) UNIQUE NOT NULL,
	PASSWORD VARCHAR(150),
	JDATE DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE ROOMS(
	ROOMID SERIAL PRIMARY KEY NOT NULL,
	USERID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
	MAXP INTEGER NOT NULL
);

CREATE TABLE MESSAGES(
	MESSAGEID SERIAL PRIMARY KEY NOT NULL,
	USERID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
	CONTEXT VARCHAR(140) NOT NULL,
	ROOMID INTEGER REFERENCES ROOMS(ROOMID) ON DELETE CASCADE
);

CREATE TABLE ENROLL(
	USERID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
	ROOMID INTEGER REFERENCES ROOMS(ROOMID) ON DELETE CASCADE
);

INSERT INTO USERS (USERNAME, PASSWORD) VALUES(
	'admin',
	'$6$rounds=603422$ZgQRx3Mm/YuUaION$b/Vwzuno1Q7e1KPWehLbRdmvdf/Bjj5.4a.fvcz3TNCl.Rn2CLbQPCsGSIBarDYHMzq3jjN8KDLkBtKJzBclf0'
);

INSERT INTO ROOMS (USERID, MAXUSER) VALUES(
	1,
	10
);

INSERT INTO ENROLL (USERID, ROOMID) VALUES(
	1,
	1
);

INSERT INTO MESSAGES (USERID, CONTEXT, ROOMID) VALUES(
	1,
	'First MSG By Admins',
	1
);
